package ai.wenjuanpro.app.feature.configlist

import ai.wenjuanpro.app.data.config.ConfigLoadResult
import ai.wenjuanpro.app.data.config.ConfigRepository
import ai.wenjuanpro.app.data.parser.ParseError
import ai.wenjuanpro.app.data.parser.ParseErrorCode
import ai.wenjuanpro.app.domain.model.Config
import ai.wenjuanpro.app.domain.session.SessionStateHolder
import ai.wenjuanpro.app.domain.usecase.LoadConfigsUseCase
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.coVerifyOrder
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.delay
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceTimeBy
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/**
 * Test skeleton for Story 1.4: 测评集选择页（首屏）— ConfigListViewModel
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 *
 * Dev MUST implement all `NotImplementedError` bodies. Each @Test maps to a designed scenario.
 * Do NOT delete any test method — if a scenario is not applicable, change to `@Ignore` with a reason comment.
 *
 * Requires: kotlinx-coroutines-test (StandardTestDispatcher + runTest) + MockK.
 */
@OptIn(ExperimentalCoroutinesApi::class)
class ConfigListViewModelTest {
    private lateinit var dispatcher: StandardTestDispatcher
    private lateinit var repo: ConfigRepository
    private lateinit var useCase: LoadConfigsUseCase
    private lateinit var session: SessionStateHolder

    @Before
    fun setUp() {
        dispatcher = StandardTestDispatcher()
        Dispatchers.setMain(dispatcher)
        repo = mockk(relaxed = false)
        useCase = mockk(relaxed = false)
        session = SessionStateHolder()
        coEvery { repo.ensureConfigDir() } returns true
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    private fun validConfig(
        configId: String = "cog-mem",
        title: String = "T",
        source: String = "$configId.txt",
        questions: Int = 5,
    ): ConfigLoadResult.Valid =
        ConfigLoadResult.Valid(
            Config(
                configId = configId,
                title = title,
                sourceFileName = source,
                questions = List(questions) { stubQuestion() },
            ),
        )

    private fun stubQuestion(): ai.wenjuanpro.app.domain.model.Question =
        ai.wenjuanpro.app.domain.model.Question.SingleChoice(
            qid = "Q1",
            mode = ai.wenjuanpro.app.domain.model.PresentMode.ALL_IN_ONE,
            stemDurationMs = null,
            optionsDurationMs = 30_000L,
            stem = ai.wenjuanpro.app.domain.model.StemContent.Text("A"),
            options =
                listOf(
                    ai.wenjuanpro.app.domain.model.OptionContent.Text("a"),
                    ai.wenjuanpro.app.domain.model.OptionContent.Text("b"),
                ),
            correctIndex = 0,
            scores = listOf(0, 0),
        )

    private fun invalidConfig(
        fileName: String = "broken.txt",
    ): ConfigLoadResult.Invalid =
        ConfigLoadResult.Invalid(
            fileName = fileName,
            errors =
                listOf(
                    ParseError(
                        line = 2,
                        field = "title",
                        code = ParseErrorCode.CONFIG_FIELD_INVALID,
                        message = "$fileName: 第 2 行缺少必填字段 title",
                    ),
                ),
        )

    private fun viewModel(): ConfigListViewModel =
        ConfigListViewModel(
            configRepository = repo,
            loadConfigs = useCase,
            sessionState = session,
            ioDispatcher = dispatcher,
        )

    private fun drainEffects(vm: ConfigListViewModel): List<ConfigListEffect> {
        val out = mutableListOf<ConfigListEffect>()
        val field =
            ConfigListViewModel::class.java.getDeclaredField("_effect").apply { isAccessible = true }
        @Suppress("UNCHECKED_CAST")
        val ch = field.get(vm) as Channel<ConfigListEffect>
        while (true) {
            val r = ch.tryReceive()
            if (r.isSuccess) out += r.getOrNull()!! else break
        }
        return out
    }

    // ============================================================
    // AC1: 展示所有 config 文件并区分有效/损坏 — Core VM scenarios
    // ============================================================

    @Test
    fun `1_4-UNIT-001 init auto-triggers Refresh and refresh runs on ioDispatcher`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns listOf(validConfig())
            val vm = viewModel()
            // Before the launched coroutine runs, state is Loading
            assertEquals(ConfigListUiState.Loading, vm.uiState.value)
            advanceUntilIdle()
            coVerify(exactly = 1) { repo.ensureConfigDir() }
            coVerify(exactly = 1) { useCase.invoke() }
            assertTrue(vm.uiState.value is ConfigListUiState.Success)
        }

    @Test
    fun `1_4-UNIT-002 Refresh with 2 valid + 1 invalid emits Success with mixed cards`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns
                listOf(
                    validConfig("cog-mem", questions = 5),
                    validConfig("emo-reg", questions = 3),
                    invalidConfig("broken.txt"),
                )
            val vm = viewModel()
            advanceUntilIdle()
            val success = vm.uiState.value as ConfigListUiState.Success
            assertEquals(3, success.cards.size)
            assertEquals(false, success.allInvalid)
            assertEquals(5, success.cards[0].questionCount)
            assertEquals(3, success.cards[1].questionCount)
            assertNull(success.cards[2].questionCount)
        }

    @Test
    fun `1_4-UNIT-003 Empty directory emits Empty state (also covers BLIND-BOUNDARY-001 N=0)`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns emptyList()
            val vm = viewModel()
            advanceUntilIdle()
            assertEquals(ConfigListUiState.Empty, vm.uiState.value)
        }

    @Test
    fun `1_4-UNIT-004 All invalid configs emits Success with allInvalid=true (not Empty)`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns
                listOf(
                    invalidConfig("a.txt"),
                    invalidConfig("b.txt"),
                    invalidConfig("c.txt"),
                )
            val vm = viewModel()
            advanceUntilIdle()
            val success = vm.uiState.value as ConfigListUiState.Success
            assertEquals(3, success.cards.size)
            assertTrue(success.allInvalid)
        }

    @Test
    fun `1_4-UNIT-005 Scan timeout beyond 5 seconds emits Timeout state`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } coAnswers {
                delay(6_000)
                listOf(validConfig())
            }
            val vm = viewModel()
            advanceTimeBy(5_001)
            advanceUntilIdle()
            assertEquals(ConfigListUiState.Timeout, vm.uiState.value)
        }

    @Test
    fun `1_4-UNIT-006 Repo throws RuntimeException emits Error and logs only class name`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } throws RuntimeException("disk full")
            val vm = viewModel()
            advanceUntilIdle()
            val err = vm.uiState.value as ConfigListUiState.Error
            assertEquals(ai.wenjuanpro.app.R.string.config_list_error_title, err.messageRes)
        }

    @Test
    fun `1_4-UNIT-007 CardClicked updates SessionStateHolder and emits NavigateToScan`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns listOf(validConfig("cog-mem"))
            val vm = viewModel()
            advanceUntilIdle()
            drainEffects(vm) // drain anything (none expected)

            vm.onIntent(ConfigListIntent.CardClicked("cog-mem"))

            assertEquals("cog-mem", session.selectedConfigId.value)
            val effects = drainEffects(vm)
            assertEquals(1, effects.size)
            assertTrue(effects.single() is ConfigListEffect.NavigateToScan)
            assertEquals("cog-mem", (effects.single() as ConfigListEffect.NavigateToScan).configId)
        }

    @Test
    fun `1_4-UNIT-008 HiddenAreaLongPressed emits NavigateToDiagnostics and preserves UiState`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns listOf(validConfig())
            val vm = viewModel()
            advanceUntilIdle()
            val before = vm.uiState.value

            vm.onIntent(ConfigListIntent.HiddenAreaLongPressed)

            val effects = drainEffects(vm)
            assertTrue(effects.contains(ConfigListEffect.NavigateToDiagnostics))
            assertEquals(before, vm.uiState.value)
        }

    @Test
    fun `1_4-UNIT-009 ViewErrors populates sheetState with invalid config errors`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns listOf(invalidConfig("broken.txt"))
            val vm = viewModel()
            advanceUntilIdle()

            vm.onIntent(ConfigListIntent.ViewErrors("broken.txt"))

            val sheet = vm.sheetState.value
            assertEquals("broken.txt", sheet?.sourceFileName)
            assertTrue((sheet?.errors ?: emptyList()).isNotEmpty())
        }

    @Test
    fun `1_4-UNIT-010 DismissSheet resets sheetState to null`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns listOf(invalidConfig("broken.txt"))
            val vm = viewModel()
            advanceUntilIdle()
            vm.onIntent(ConfigListIntent.ViewErrors("broken.txt"))
            assertTrue(vm.sheetState.value != null)

            vm.onIntent(ConfigListIntent.DismissSheet)

            assertNull(vm.sheetState.value)
        }

    @Test
    fun `1_4-UNIT-011 ensureConfigDir is called BEFORE loadConfigs in refresh()`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns emptyList()
            val vm = viewModel()
            advanceUntilIdle()
            coVerifyOrder {
                repo.ensureConfigDir()
                useCase.invoke()
            }
        }

    @Test
    fun `1_4-UNIT-012 Refresh during Loading is idempotent (no double invocation)`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } coAnswers {
                delay(1_000)
                emptyList()
            }
            val vm = viewModel()
            // init already fires Refresh once; send another immediately while in-flight
            vm.onIntent(ConfigListIntent.Refresh)
            advanceUntilIdle()
            coVerify(exactly = 1) { useCase.invoke() }
        }

    // ============================================================
    // [BLIND-SPOT] scenarios for VM
    // ============================================================

    @Test
    fun `1_4-BLIND-ERROR-001 SecurityException from repo is caught and mapped to Error state`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } throws SecurityException("permission revoked")
            val vm = viewModel()
            advanceUntilIdle()
            val err = vm.uiState.value as ConfigListUiState.Error
            assertEquals(ai.wenjuanpro.app.R.string.config_list_error_title, err.messageRes)
        }

    @Test
    fun `1_4-BLIND-ERROR-004 Retry after Timeout resets state and re-invokes ensureConfigDir + loadConfigs`() =
        runTest(dispatcher) {
            var call = 0
            coEvery { useCase.invoke() } coAnswers {
                call++
                if (call == 1) {
                    delay(6_000)
                    emptyList()
                } else {
                    emptyList()
                }
            }
            val vm = viewModel()
            advanceTimeBy(5_001)
            advanceUntilIdle()
            assertEquals(ConfigListUiState.Timeout, vm.uiState.value)

            vm.onIntent(ConfigListIntent.Refresh)
            advanceUntilIdle()

            assertEquals(ConfigListUiState.Empty, vm.uiState.value)
            coVerify(exactly = 2) { repo.ensureConfigDir() }
            coVerify(exactly = 2) { useCase.invoke() }
        }

    @Test
    fun `1_4-BLIND-FLOW-001 Rapid duplicate CardClicked emits NavigateToScan only once`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } returns listOf(validConfig("cog-mem"))
            val vm = viewModel()
            advanceUntilIdle()

            vm.onIntent(ConfigListIntent.CardClicked("cog-mem"))
            vm.onIntent(ConfigListIntent.CardClicked("cog-mem"))
            advanceUntilIdle()

            val effects = drainEffects(vm)
            assertEquals(1, effects.count { it is ConfigListEffect.NavigateToScan })
        }

    @Test
    fun `1_4-BLIND-FLOW-002 viewModelScope cancellation mid-scan is safe (no NPE, no stale write)`() =
        runTest(dispatcher) {
            coEvery { useCase.invoke() } coAnswers {
                delay(10_000)
                listOf(validConfig())
            }
            val vm = viewModel()
            // Force onCleared by reflection: viewModelScope will be cancelled on onCleared
            val method = androidx.lifecycle.ViewModel::class.java.getDeclaredMethod("clear").apply {
                isAccessible = true
            }
            method.invoke(vm)
            advanceUntilIdle()
            // After cancellation, state should not be written to Success/Timeout/Error from the cancelled run
            // The in-flight coroutine was cancelled before advanceTimeBy passed the 5s timeout boundary.
            assertEquals(ConfigListUiState.Loading, vm.uiState.value)
        }
}
