package ai.wenjuanpro.app.feature.configlist

import ai.wenjuanpro.app.data.config.ConfigLoadResult
import ai.wenjuanpro.app.data.parser.ParseError
import ai.wenjuanpro.app.data.parser.ParseErrorCode
import ai.wenjuanpro.app.domain.model.Config
import ai.wenjuanpro.app.domain.model.PresentMode
import ai.wenjuanpro.app.domain.model.Question
import ai.wenjuanpro.app.domain.model.StemContent
import ai.wenjuanpro.app.domain.model.OptionContent
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Test skeleton for Story 1.4 — ConfigLoadResult → ConfigCardUiModel mapping.
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 */
class ConfigListUiMapperTest {
    private fun q(id: String = "Q1"): Question =
        Question.SingleChoice(
            qid = id,
            mode = PresentMode.ALL_IN_ONE,
            stemDurationMs = null,
            optionsDurationMs = 30_000L,
            stem = StemContent.Text("A"),
            options = listOf(OptionContent.Text("a"), OptionContent.Text("b")),
            correctIndex = 0,
            scores = listOf(0, 0),
        )

    private fun validResult(
        configId: String = "cog-mem",
        title: String = "T",
        source: String = "cog-mem.txt",
        count: Int = 5,
    ): ConfigLoadResult.Valid =
        ConfigLoadResult.Valid(
            Config(
                configId = configId,
                title = title,
                sourceFileName = source,
                questions = List(count) { q("Q${it + 1}") },
            ),
        )

    private fun invalidResult(
        fileName: String = "broken.txt",
        errors: List<ParseError> =
            listOf(
                ParseError(
                    line = 2,
                    field = "title",
                    code = ParseErrorCode.CONFIG_FIELD_INVALID,
                    message = "$fileName: 第 2 行缺少必填字段 title",
                ),
            ),
    ): ConfigLoadResult.Invalid = ConfigLoadResult.Invalid(fileName = fileName, errors = errors)

    @Test
    fun `1_4-UNIT-013 Valid ConfigLoadResult maps to ConfigCardUiModel with isValid=true`() {
        val cards = ConfigListUiMapper.toCards(listOf(validResult(count = 5)))
        val card = cards.single()
        assertEquals("cog-mem", card.configId)
        assertEquals("T", card.title)
        assertEquals(5, card.questionCount)
        assertTrue(card.isValid)
        assertTrue(card.errors.isEmpty())
        assertEquals("cog-mem.txt", card.sourceFileName)
    }

    @Test
    fun `1_4-UNIT-014 Invalid ConfigLoadResult maps to ConfigCardUiModel with isValid=false and null questionCount`() {
        val cards = ConfigListUiMapper.toCards(listOf(invalidResult()))
        val card = cards.single()
        assertEquals("broken", card.configId)
        assertEquals("broken.txt", card.title)
        assertNull(card.questionCount)
        assertEquals(false, card.isValid)
        assertTrue(card.errors.isNotEmpty())
        assertEquals("broken.txt", card.sourceFileName)
    }

    @Test
    fun `1_4-UNIT-015 sourceFileName is preserved as LazyColumn key for both branches`() {
        val valid = validResult(configId = "cog-mem", source = "cog-mem.txt")
        val invalid = invalidResult(fileName = "broken.txt")
        val cards = ConfigListUiMapper.toCards(listOf(valid, invalid))
        assertEquals(listOf("cog-mem.txt", "broken.txt"), cards.map { it.sourceFileName })
    }

    @Test
    fun `1_4-BLIND-BOUNDARY-004 Config with 0 questions maps to questionCount=0 (not null)`() {
        val cards = ConfigListUiMapper.toCards(listOf(validResult(count = 0)))
        val card = cards.single()
        assertEquals(0, card.questionCount)
        assertTrue(card.isValid)
    }
}
