package ai.wenjuanpro.app.domain.session

import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.take
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Test skeleton for Story 1.4 — SessionStateHolder (@ActivityRetainedScoped).
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 */
@OptIn(ExperimentalCoroutinesApi::class)
class SessionStateHolderTest {
    @Test
    fun `1_4-UNIT-016 selectConfig updates selectedConfigId StateFlow value`() {
        val holder = SessionStateHolder()
        holder.selectConfig("cog-mem")
        assertEquals("cog-mem", holder.selectedConfigId.value)
    }

    @Test
    fun `1_4-UNIT-017 clear resets selectedConfigId to null`() {
        val holder = SessionStateHolder()
        holder.selectConfig("cog-mem")
        holder.clear()
        assertNull(holder.selectedConfigId.value)
    }

    @Test
    fun `1_4-UNIT-018 StateFlow subscribers observe selectConfig updates`() =
        runTest(StandardTestDispatcher(testScheduler)) {
            val holder = SessionStateHolder()
            val collected = mutableListOf<String?>()
            val job =
                launch {
                    holder.selectedConfigId.take(2).toList(collected)
                }
            advanceUntilIdle()
            holder.selectConfig("cog-mem")
            advanceUntilIdle()
            job.join()
            assertEquals(listOf(null, "cog-mem"), collected)
        }
}
