package ai.wenjuanpro.app.core.io

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

/**
 * Test skeleton for Story 1.4 — OkioFileSystem.mkdirs extension.
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 *
 * Uses JUnit4 TemporaryFolder for real filesystem assertions (no mocks; `mkdirs` wraps java.io.File).
 */
class OkioFileSystemMkdirsTest {
    @get:Rule
    val tempFolder = TemporaryFolder()

    @Test
    fun `1_4-INT-001 mkdirs creates nested directory and returns true when path does not exist`() {
        val fs = OkioFileSystem()
        val target = File(tempFolder.root, "nested/deep").absolutePath

        val result = fs.mkdirs(target)

        assertTrue(result)
        assertTrue(File(target).exists())
        assertTrue(File(target).isDirectory)
    }

    @Test
    fun `1_4-INT-002 mkdirs on already-existing directory returns true without exception`() {
        val fs = OkioFileSystem()
        val existing = tempFolder.newFolder("already")
        val path = existing.absolutePath

        val result = fs.mkdirs(path)

        assertTrue(result)
        assertTrue(File(path).isDirectory)
    }

    @Test
    fun `1_4-INT-003 mkdirs returns false when parent path is a regular file (not directory)`() {
        val fs = OkioFileSystem()
        val file = tempFolder.newFile("blocker")
        val target = File(file, "childDir").absolutePath

        val result = fs.mkdirs(target)

        assertFalse(result)
        assertFalse(File(target).isDirectory)
    }
}
