package ai.wenjuanpro.app.core.io

import okio.Buffer
import okio.ForwardingFileSystem
import okio.Path
import okio.Source
import okio.Timeout
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.IOException
import java.util.concurrent.atomic.AtomicInteger
import okio.FileSystem as OkioFs

/**
 * Test Skeleton for Story 1.3 — OkioFileSystem.
 *
 * AUTO-GENERATED by QA Test Design (Turing, 2026-04-17). Dev MUST implement every test block.
 * Scenarios map to docs/qa/assessments/1.3-test-design-20260417.md.
 *
 * These tests run on the JVM (no Robolectric needed) using JUnit4 TemporaryFolder for real IO.
 */
class OkioFileSystemTest {
    @get:Rule
    val tempDir: TemporaryFolder = TemporaryFolder()

    // ============================================================
    // AC1 — Core Integration
    // ============================================================

    @Test
    fun `1_3-INT-007 readBytes returns exact bytes of a real file`() {
        val file = tempDir.newFile("hello.txt")
        val expected = "hello\n".toByteArray(Charsets.UTF_8)
        file.writeBytes(expected)
        val fs = OkioFileSystem()
        val actual = fs.readBytes(file.absolutePath)
        assertArrayEquals(expected, actual)
    }

    @Test
    fun `1_3-INT-008 listFiles returns only files with txt suffix`() {
        tempDir.newFile("a.txt")
        tempDir.newFile("b.md")
        tempDir.newFile("c.TXT")
        tempDir.newFile("d.txt")
        val fs = OkioFileSystem()
        val names =
            fs.listFiles(tempDir.root.absolutePath, ".txt")
                .map { it.substringAfterLast('/') }
                .toSet()
        assertEquals(setOf("a.txt", "d.txt"), names)
    }

    @Test
    fun `1_3-INT-009 exists returns true for existing and false for missing paths`() {
        val file = tempDir.newFile("present.txt")
        val fs = OkioFileSystem()
        assertTrue(fs.exists(file.absolutePath))
        assertFalse(fs.exists(tempDir.root.absolutePath + "/missing.txt"))
    }

    // ============================================================
    // AC1 — [BLIND-SPOT] RESOURCE
    // ============================================================

    @Test
    fun `1_3-BLIND-RESOURCE-001 readBytes closes source on happy path`() {
        val file = tempDir.newFile("res-ok.txt")
        file.writeBytes("x".toByteArray())
        val tracking = TrackingFileSystem(OkioFs.SYSTEM)
        val fs = OkioFileSystem(tracking)
        fs.readBytes(file.absolutePath)
        assertEquals(1, tracking.closeCount.get())
    }

    @Test
    fun `1_3-BLIND-RESOURCE-002 readBytes closes source on exception`() {
        val file = tempDir.newFile("res-err.txt")
        file.writeBytes("x".toByteArray())
        val tracking = TrackingFileSystem(OkioFs.SYSTEM, throwOnRead = true)
        val fs = OkioFileSystem(tracking)
        try {
            fs.readBytes(file.absolutePath)
            fail("expected IOException")
        } catch (_: IOException) {
            // expected
        }
        assertTrue(
            "source must be closed on exception path",
            tracking.closeCount.get() >= 1,
        )
    }

    // ---- Helpers ----

    private class TrackingFileSystem(
        delegate: OkioFs,
        private val throwOnRead: Boolean = false,
    ) : ForwardingFileSystem(delegate) {
        val closeCount = AtomicInteger(0)

        override fun source(file: Path): Source {
            val inner = super.source(file)
            return object : Source {
                override fun read(sink: Buffer, byteCount: Long): Long {
                    if (throwOnRead) throw IOException("boom")
                    return inner.read(sink, byteCount)
                }

                override fun timeout(): Timeout = inner.timeout()

                override fun close() {
                    closeCount.incrementAndGet()
                    inner.close()
                }
            }
        }
    }
}
