package ai.wenjuanpro.app.data.parser

import ai.wenjuanpro.app.core.io.FileSystem
import ai.wenjuanpro.app.domain.model.OptionContent
import ai.wenjuanpro.app.domain.model.PresentMode
import ai.wenjuanpro.app.domain.model.Question
import ai.wenjuanpro.app.domain.model.StemContent
import io.mockk.every
import io.mockk.mockk
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import java.nio.charset.Charset

/**
 * Test Skeleton for Story 1.3: TXT config 解析器与 schema 校验 — ConfigParser.
 *
 * AUTO-GENERATED by QA Test Design (Turing, 2026-04-17). Dev MUST implement every test block.
 * Do NOT delete any test method — each maps to a designed scenario in
 * docs/qa/assessments/1.3-test-design-20260417.md.
 * If a scenario is truly inapplicable, change to `@Ignore` with a reason comment.
 */
class ConfigParserTest {
    private lateinit var fs: FileSystem
    private lateinit var parser: ConfigParser

    @Before
    fun setUp() {
        fs = mockk(relaxed = true)
        every { fs.exists(any()) } returns true // default: all assets exist unless overridden
        parser = ConfigParser(fs)
    }

    // ---------- Fixtures ----------

    private fun validSingle(
        configId: String = "cog-mem-2026q3",
        title: String = "认知记忆测评 v1",
        type: String = "single",
        mode: String = "all_in_one",
        durationLine: String = "durationMs: 30000",
        stem: String = "你今天感觉如何？",
        options: String = "很好|一般|较差|很差",
        correct: String = "1",
        score: String = "0|0|0|0",
        sourceName: String = "cog-mem-2026q3.txt",
    ): Pair<String, String> {
        val body =
            """
            # configId: $configId
            # title: $title
            [Q1]
            type: $type
            mode: $mode
            $durationLine
            stem: $stem
            options: $options
            correct: $correct
            score: $score
            """.trimIndent()
        return body to sourceName
    }

    private fun parse(body: String, sourceName: String = "cog-mem-2026q3.txt"): ParseResult =
        parser.parse(sourceName, body.toByteArray(Charsets.UTF_8))

    // ============================================================
    // AC1 — Core Unit: Happy Path 与结构性
    // ============================================================

    @Test
    fun `1_3-UNIT-001 parse single-choice AC1 example 1 returns Success with full field assertions`() {
        val (body, src) = validSingle()
        val result = parse(body, src)
        assertTrue(result is ParseResult.Success)
        val config = (result as ParseResult.Success).config
        assertEquals("cog-mem-2026q3", config.configId)
        assertEquals("认知记忆测评 v1", config.title)
        assertEquals(1, config.questions.size)
        val q = config.questions[0] as Question.SingleChoice
        assertEquals("Q1", q.qid)
        assertEquals(PresentMode.ALL_IN_ONE, q.mode)
        assertEquals(30000L, q.optionsDurationMs)
        assertEquals(1, q.correctIndex)
        assertEquals(listOf(0, 0, 0, 0), q.scores)
        assertEquals(4, q.options.size)
    }

    @Test
    fun `1_3-UNIT-002 parse multi-choice correct 1 3 returns Success with correctIndices set`() {
        val body =
            """
            # configId: multi-ok
            # title: Multi
            [Q1]
            type: multi
            mode: all_in_one
            durationMs: 30000
            stem: Question
            options: a|b|c|d
            correct: 1,3
            score: 1|0|1|0
            """.trimIndent()
        val result = parse(body, "multi-ok.txt")
        assertTrue(result is ParseResult.Success)
        val q = (result as ParseResult.Success).config.questions[0] as Question.MultiChoice
        assertEquals(setOf(1, 3), q.correctIndices)
        assertEquals(q.options.size, q.scores.size)
    }

    @Test
    fun `1_3-UNIT-003 parse memory question with valid dotsPositions returns Success`() {
        val body =
            """
            # configId: mem-ok
            # title: Memory
            [Q1]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 3,7,12,19,22,30,37,44,51,58
            """.trimIndent()
        val result = parse(body, "mem-ok.txt")
        assertTrue("Expected Success, was $result", result is ParseResult.Success)
        val q = (result as ParseResult.Success).config.questions[0] as Question.Memory
        assertEquals(10, q.dotsPositions.size)
        assertEquals(10, q.dotsPositions.toSet().size)
        assertTrue(q.dotsPositions.all { it in 0..63 })
    }

    @Test
    fun `1_3-UNIT-004 parse three sequential sections Q1 Q2 Q3 preserves order`() {
        val body =
            """
            # configId: mix-ok
            # title: Mix
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            [Q2]
            type: multi
            mode: all_in_one
            durationMs: 30000
            stem: B
            options: a|b|c
            correct: 1,2
            score: 0|0|0
            [Q3]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 0,7,12,19,22,30,37,44,51,63
            """.trimIndent()
        val result = parse(body, "mix-ok.txt")
        assertTrue("Expected Success, was $result", result is ParseResult.Success)
        val questions = (result as ParseResult.Success).config.questions
        assertEquals(3, questions.size)
        assertEquals(listOf("Q1", "Q2", "Q3"), questions.map { it.qid })
    }

    // ============================================================
    // AC1 — Core Unit: Header / BR-1.1 / BR-1.2
    // ============================================================

    @Test
    fun `1_3-UNIT-005 header missing title fails with CONFIG_HEADER_MISSING`() {
        val body =
            """
            # configId: cog-mem-2026q3
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val result = parse(body)
        assertTrue(result is ParseResult.Failure)
        val errors = (result as ParseResult.Failure).errors
        assertTrue(errors.any { it.field == "title" && it.code == ParseErrorCode.CONFIG_HEADER_MISSING })
    }

    @Test
    fun `1_3-UNIT-006 header missing configId falls back to filename when title present`() {
        val body =
            """
            # title: 认知记忆测评 v1
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val result = parse(body, "cog-mem-2026q3.txt")
        assertTrue("Expected Success, was $result", result is ParseResult.Success)
        assertEquals("cog-mem-2026q3", (result as ParseResult.Success).config.configId)
    }

    @Test
    fun `1_3-UNIT-007 header missing both configId and title aggregates two errors`() {
        val body =
            """
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val result = parse(body)
        assertTrue(result is ParseResult.Failure)
        val errors = (result as ParseResult.Failure).errors
        assertTrue(errors.any { it.field == "configId" })
        assertTrue(errors.any { it.field == "title" })
    }

    // ============================================================
    // AC1 — Core Unit: BR-1.4 Options / Stem 图文混合
    // ============================================================

    @Test
    fun `1_3-UNIT-008 options with img and text mixed parsed to correct OptionContent variants`() {
        every { fs.exists(any()) } returns true
        val body =
            """
            # configId: opt-mix
            # title: Opt
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: hi
            options: img:a.png|苹果|img:b.png|很好
            correct: 1
            score: 0|0|0|0
            """.trimIndent()
        val result = parse(body, "opt-mix.txt")
        assertTrue("Expected Success, was $result", result is ParseResult.Success)
        val q = (result as ParseResult.Success).config.questions[0] as Question.SingleChoice
        assertEquals(4, q.options.size)
        assertTrue(q.options[0] is OptionContent.Image)
        assertEquals("a.png", (q.options[0] as OptionContent.Image).fileName)
        assertTrue(q.options[1] is OptionContent.Text)
        assertEquals("苹果", (q.options[1] as OptionContent.Text).text)
        assertTrue(q.options[2] is OptionContent.Image)
        assertTrue(q.options[3] is OptionContent.Text)
    }

    @Test
    fun `1_3-UNIT-009 stem with img and text parses to StemContent Mixed`() {
        val body =
            """
            # configId: stem-mix
            # title: Stem
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: img:banner.png|提示
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val result = parse(body, "stem-mix.txt")
        assertTrue(result is ParseResult.Success)
        val q = (result as ParseResult.Success).config.questions[0] as Question.SingleChoice
        assertTrue(q.stem is StemContent.Mixed)
        val parts = (q.stem as StemContent.Mixed).parts
        assertEquals(2, parts.size)
        assertTrue(parts[0] is StemContent.Image)
        assertTrue(parts[1] is StemContent.Text)
    }

    // ============================================================
    // AC1 — Core Unit: BR-1.6 BOM / Encoding
    // ============================================================

    @Test
    fun `1_3-UNIT-010 BOM prefix plus valid body returns Success with BOM warning`() {
        val (body, src) = validSingle()
        val bodyBytes = body.toByteArray(Charsets.UTF_8)
        val bomPrefixed = byteArrayOf(0xEF.toByte(), 0xBB.toByte(), 0xBF.toByte()) + bodyBytes
        val result = parser.parse(src, bomPrefixed)
        assertTrue("Expected Success, was $result", result is ParseResult.Success)
        val config = (result as ParseResult.Success).config
        assertEquals(1, config.parseWarnings.size)
        assertEquals(1, config.parseWarnings[0].line)
    }

    // ============================================================
    // AC1 — Core Unit: Data Validation
    // ============================================================

    @Test
    fun `1_3-UNIT-011 unknown type fails with CONFIG_FIELD_INVALID field type`() {
        val (body, src) = validSingle(type = "foo")
        val result = parse(body, src)
        assertTrue(result is ParseResult.Failure)
        val err = (result as ParseResult.Failure).errors.first { it.field == "type" }
        assertEquals(ParseErrorCode.CONFIG_FIELD_INVALID, err.code)
        assertTrue(
            "message should contain legal values: ${err.message}",
            err.message.contains("single/multi/memory"),
        )
    }

    @Test
    fun `1_3-UNIT-012 unknown mode fails with CONFIG_FIELD_INVALID field mode`() {
        val (body, src) = validSingle(mode = "foo")
        val result = parse(body, src)
        assertTrue(result is ParseResult.Failure)
        val err = (result as ParseResult.Failure).errors.first { it.field == "mode" }
        assertEquals(ParseErrorCode.CONFIG_FIELD_INVALID, err.code)
        assertTrue(err.message.contains("all_in_one/staged"))
    }

    @Test
    fun `1_3-UNIT-013 all_in_one missing durationMs fails`() {
        val body =
            """
            # configId: no-dur
            # title: X
            [Q1]
            type: single
            mode: all_in_one
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val result = parse(body, "no-dur.txt")
        assertTrue(result is ParseResult.Failure)
        assertTrue(
            (result as ParseResult.Failure).errors.any { it.field == "durationMs" },
        )
    }

    @Test
    fun `1_3-UNIT-014 staged missing stemDurationMs fails`() {
        val body =
            """
            # configId: staged-a
            # title: S
            [Q1]
            type: single
            mode: staged
            optionsDurationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val result = parse(body, "staged-a.txt")
        assertTrue(result is ParseResult.Failure)
        assertTrue((result as ParseResult.Failure).errors.any { it.field == "stemDurationMs" })
    }

    @Test
    fun `1_3-UNIT-015 staged missing optionsDurationMs fails`() {
        val body =
            """
            # configId: staged-b
            # title: S
            [Q1]
            type: single
            mode: staged
            stemDurationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val result = parse(body, "staged-b.txt")
        assertTrue(result is ParseResult.Failure)
        assertTrue((result as ParseResult.Failure).errors.any { it.field == "optionsDurationMs" })
    }

    // ============================================================
    // AC1 — Core Unit: 错误聚合 / 行号
    // ============================================================

    @Test
    fun `1_3-UNIT-016 three independent violations aggregate into three errors without short circuit`() {
        // 1. header missing title
        // 2. invalid type in [Q1]
        // 3. dotsPositions count wrong in [Q2] (memory)
        val body =
            """
            # configId: bad-agg
            [Q1]
            type: unknown
            mode: all_in_one
            durationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            [Q2]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 1,2,3
            """.trimIndent()
        val result = parse(body, "bad-agg.txt")
        assertTrue(result is ParseResult.Failure)
        val errors = (result as ParseResult.Failure).errors
        assertTrue("Expected >= 3 errors, got ${errors.size}: $errors", errors.size >= 3)
        assertTrue(errors.any { it.field == "title" })
        assertTrue(errors.any { it.field == "type" })
        assertTrue(errors.any { it.field == "dotsPositions" })
    }

    @Test
    fun `1_3-UNIT-017 line numbers on ParseError are 1-based and match source lines`() {
        // line 1: # configId: ok
        // line 2: # title: Hi
        // line 3: [Q1]
        // line 4: type: foo        <-- error at line 4
        // line 5: mode: all_in_one
        // ... (skipped because type failed)
        // line 11: [Q2]
        // line 12: type: multi
        // line 13: mode: bad       <-- error at line 13
        val body =
            """
            # configId: ok
            # title: Hi
            [Q1]
            type: foo
            mode: all_in_one
            durationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            [Q2]
            type: multi
            mode: bad
            stemDurationMs: 1000
            optionsDurationMs: 1000
            stem: B
            options: a|b
            correct: 1,2
            score: 0|0
            """.trimIndent()
        val result = parse(body, "lines.txt")
        assertTrue(result is ParseResult.Failure)
        val errors = (result as ParseResult.Failure).errors
        val typeErr = errors.first { it.field == "type" }
        val modeErr = errors.first { it.field == "mode" }
        assertEquals(4, typeErr.line)
        assertEquals(13, modeErr.line)

        // ENCODING_INVALID uses line=0, null field
        val gbkBytes =
            "# configId: ok\n# title: 你好\n".toByteArray(Charset.forName("GBK")) +
                "[Q1]\ntype: single\nmode: all_in_one\ndurationMs: 30000\n".toByteArray(Charsets.UTF_8)
        val encResult = parser.parse("gbk.txt", gbkBytes)
        assertTrue(encResult is ParseResult.Failure)
        val encErr = (encResult as ParseResult.Failure).errors.first()
        assertEquals(ParseErrorCode.ENCODING_INVALID, encErr.code)
        assertEquals(0, encErr.line)
        assertEquals(null, encErr.field)
    }

    // ============================================================
    // AC1 — Core Unit: 题型/字段边界
    // ============================================================

    @Test
    fun `1_3-UNIT-018 multi choice correct descending 3 1 ascending policy decision`() {
        // Dev decision: strictly ascending required → Failure. Documented in Dev Log.
        val body =
            """
            # configId: multi-desc
            # title: X
            [Q1]
            type: multi
            mode: all_in_one
            durationMs: 30000
            stem: A
            options: a|b|c|d
            correct: 3,1
            score: 0|0|0|0
            """.trimIndent()
        val result = parse(body, "multi-desc.txt")
        assertTrue("Expected Failure per ascending policy, was $result", result is ParseResult.Failure)
        assertTrue(
            (result as ParseResult.Failure).errors.any {
                it.field == "correct" && it.code == ParseErrorCode.CONFIG_FIELD_INVALID
            },
        )
    }

    @Test
    fun `1_3-UNIT-019 mixed CRLF and LF line endings parse with correct line numbers`() {
        // line 1: # configId: ok
        // line 2: # title: Hi
        // line 3: [Q1]
        // line 4: type: foo   <-- error
        val raw =
            "# configId: ok\r\n" +
                "# title: Hi\n" +
                "[Q1]\r\n" +
                "type: foo\n" +
                "mode: all_in_one\n" +
                "durationMs: 30000\n" +
                "stem: A\n" +
                "options: a|b\n" +
                "correct: 1\n" +
                "score: 0|0\n"
        val result = parser.parse("mixed.txt", raw.toByteArray(Charsets.UTF_8))
        assertTrue(result is ParseResult.Failure)
        val err = (result as ParseResult.Failure).errors.first { it.field == "type" }
        assertEquals(4, err.line)
    }

    @Test
    fun `1_3-UNIT-020 comment and blank lines inside section are skipped without shifting line numbers`() {
        // line 1: # configId: ok
        // line 2: # title: Hi
        // line 3: [Q1]
        // line 4: # note
        // line 5: (blank)
        // line 6: type: single
        // line 7: mode: all_in_one
        // line 8: durationMs: 30000
        // line 9: stem: A
        // line 10: options: a|b|c|d
        // line 11: correct: 99   <-- error at line 11 (out of range)
        // line 12: score: 0|0|0|0
        val body =
            "# configId: ok\n" +
                "# title: Hi\n" +
                "[Q1]\n" +
                "# note\n" +
                "\n" +
                "type: single\n" +
                "mode: all_in_one\n" +
                "durationMs: 30000\n" +
                "stem: A\n" +
                "options: a|b|c|d\n" +
                "correct: 99\n" +
                "score: 0|0|0|0\n"
        val result = parser.parse("cmt.txt", body.toByteArray(Charsets.UTF_8))
        assertTrue(result is ParseResult.Failure)
        val err = (result as ParseResult.Failure).errors.first { it.field == "correct" }
        assertEquals(11, err.line)
    }

    @Test
    fun `1_3-UNIT-021 options with empty component a pipe pipe b fails`() {
        val (body, src) = validSingle(options = "a||b", score = "0|0|0", correct = "1")
        val result = parse(body, src)
        assertTrue(result is ParseResult.Failure)
        assertTrue((result as ParseResult.Failure).errors.any { it.field == "options" })
    }

    @Test
    fun `1_3-UNIT-022 correct index out of range fails`() {
        val (body, src) = validSingle(correct = "5")
        val result = parse(body, src)
        assertTrue(result is ParseResult.Failure)
        assertTrue((result as ParseResult.Failure).errors.any { it.field == "correct" })
    }

    @Test
    fun `1_3-UNIT-023 score length mismatch options length fails`() {
        val (body, src) = validSingle(score = "0|0|0")
        val result = parse(body, src)
        assertTrue(result is ParseResult.Failure)
        assertTrue((result as ParseResult.Failure).errors.any { it.field == "score" })
    }

    @Test
    fun `1_3-UNIT-024 duplicate Q1 section header fails with field qid`() {
        val body =
            """
            # configId: dup
            # title: D
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: A
            options: a|b
            correct: 1
            score: 0|0
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: B
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val result = parse(body, "dup.txt")
        assertTrue(result is ParseResult.Failure)
        assertTrue((result as ParseResult.Failure).errors.any { it.field == "qid" })
    }

    @Test
    fun `1_3-UNIT-025 invalid Qn header formats Q Q0 Q1a all fail`() {
        for (header in listOf("[Q]", "[Q0]", "[Q1a]")) {
            val body =
                """
                # configId: bad-qid
                # title: X
                $header
                type: single
                mode: all_in_one
                durationMs: 30000
                stem: A
                options: a|b
                correct: 1
                score: 0|0
                """.trimIndent()
            val result = parse(body, "bad-qid.txt")
            assertTrue("Expected Failure for $header, was $result", result is ParseResult.Failure)
            assertTrue(
                "Expected field=qid error for $header",
                (result as ParseResult.Failure).errors.any { it.field == "qid" },
            )
        }
    }

    @Test
    fun `1_3-UNIT-026 empty file or header only file fails`() {
        val emptyResult = parser.parse("empty.txt", ByteArray(0))
        assertTrue(emptyResult is ParseResult.Failure)
        assertTrue(
            (emptyResult as ParseResult.Failure).errors.any { it.message.contains("至少包含一道题") },
        )

        val headerOnly =
            """
            # configId: hdr
            # title: Only
            """.trimIndent()
        val hdrResult = parse(headerOnly, "hdr.txt")
        assertTrue(hdrResult is ParseResult.Failure)
        assertTrue(
            (hdrResult as ParseResult.Failure).errors.any { it.message.contains("至少包含一道题") },
        )
    }

    // ============================================================
    // AC1 — [BLIND-SPOT] BOUNDARY
    // ============================================================

    @Test
    fun `1_3-BLIND-BOUNDARY-001 configId length 1 minimum boundary succeeds`() {
        val (body, src) = validSingle(configId = "a")
        assertTrue(parse(body, src) is ParseResult.Success)
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-002 configId length 64 maximum boundary succeeds`() {
        val id = "a".repeat(64)
        val (body, src) = validSingle(configId = id)
        val r = parse(body, src)
        assertTrue("Expected Success, was $r", r is ParseResult.Success)
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-003 configId length 65 just beyond maximum fails`() {
        val id = "a".repeat(65)
        val (body, src) = validSingle(configId = id)
        val r = parse(body, src)
        assertTrue(r is ParseResult.Failure)
        assertTrue((r as ParseResult.Failure).errors.any { it.field == "configId" })
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-004 durationMs at minimum 1000 succeeds`() {
        val (body, src) = validSingle(durationLine = "durationMs: 1000")
        assertTrue(parse(body, src) is ParseResult.Success)
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-005 durationMs at maximum 600000 succeeds`() {
        val (body, src) = validSingle(durationLine = "durationMs: 600000")
        assertTrue(parse(body, src) is ParseResult.Success)
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-006 durationMs 999 just below minimum fails`() {
        val (body, src) = validSingle(durationLine = "durationMs: 999")
        val r = parse(body, src)
        assertTrue(r is ParseResult.Failure)
        assertTrue((r as ParseResult.Failure).errors.any { it.field == "durationMs" })
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-007 durationMs 600001 just above maximum fails`() {
        val (body, src) = validSingle(durationLine = "durationMs: 600001")
        val r = parse(body, src)
        assertTrue(r is ParseResult.Failure)
        assertTrue((r as ParseResult.Failure).errors.any { it.field == "durationMs" })
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-008 dotsPositions contains minimum index 0 succeeds`() {
        val body =
            """
            # configId: mem-min
            # title: M
            [Q1]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 0,7,12,19,22,30,37,44,51,58
            """.trimIndent()
        val r = parse(body, "mem-min.txt")
        assertTrue("Expected Success, was $r", r is ParseResult.Success)
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-009 dotsPositions contains maximum index 63 succeeds`() {
        val body =
            """
            # configId: mem-max
            # title: M
            [Q1]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 3,7,12,19,22,30,37,44,51,63
            """.trimIndent()
        assertTrue(parse(body, "mem-max.txt") is ParseResult.Success)
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-010 dotsPositions contains 64 just beyond maximum fails`() {
        val body =
            """
            # configId: mem-64
            # title: M
            [Q1]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 3,7,12,19,22,30,37,44,51,64
            """.trimIndent()
        val r = parse(body, "mem-64.txt")
        assertTrue(r is ParseResult.Failure)
        assertTrue((r as ParseResult.Failure).errors.any { it.field == "dotsPositions" })
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-011 dotsPositions with only 9 items fails`() {
        val body =
            """
            # configId: mem-9
            # title: M
            [Q1]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 3,7,12,19,22,30,37,44,51
            """.trimIndent()
        val r = parse(body, "mem-9.txt")
        assertTrue(r is ParseResult.Failure)
        assertTrue((r as ParseResult.Failure).errors.any { it.field == "dotsPositions" })
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-012 dotsPositions with 11 items fails`() {
        val body =
            """
            # configId: mem-11
            # title: M
            [Q1]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 3,7,12,19,22,30,37,44,51,58,60
            """.trimIndent()
        val r = parse(body, "mem-11.txt")
        assertTrue(r is ParseResult.Failure)
        assertTrue((r as ParseResult.Failure).errors.any { it.field == "dotsPositions" })
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-013 dotsPositions contains duplicate indices fails`() {
        val body =
            """
            # configId: mem-dup
            # title: M
            [Q1]
            type: memory
            mode: all_in_one
            durationMs: 30000
            dotsPositions: 3,3,12,19,22,30,37,44,51,58
            """.trimIndent()
        val r = parse(body, "mem-dup.txt")
        assertTrue(r is ParseResult.Failure)
        assertTrue((r as ParseResult.Failure).errors.any { it.field == "dotsPositions" })
    }

    @Test
    fun `1_3-BLIND-BOUNDARY-014 configId with illegal characters fails`() {
        for (id in listOf("中文测试", "has space", "bad@char")) {
            val (body, src) = validSingle(configId = id)
            val r = parse(body, src)
            assertTrue("Expected Failure for $id, was $r", r is ParseResult.Failure)
            assertTrue(
                "Expected field=configId error for $id",
                (r as ParseResult.Failure).errors.any { it.field == "configId" },
            )
        }
    }

    // ============================================================
    // AC1 — [BLIND-SPOT] ERROR (parser-level)
    // ============================================================

    @Test
    fun `1_3-BLIND-ERROR-001 asset image in options missing produces ASSET_NOT_FOUND`() {
        every { fs.exists(any()) } returns true
        every { fs.exists("/sdcard/WenJuanPro/assets/a.png") } returns false
        val body =
            """
            # configId: asset-opt
            # title: X
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: hi
            options: img:a.png|b|c|d
            correct: 2
            score: 0|0|0|0
            """.trimIndent()
        val r = parse(body, "asset-opt.txt")
        assertTrue(r is ParseResult.Failure)
        val err = (r as ParseResult.Failure).errors.first { it.code == ParseErrorCode.ASSET_NOT_FOUND }
        assertEquals("options", err.field)
    }

    @Test
    fun `1_3-BLIND-ERROR-002 asset image in stem missing produces ASSET_NOT_FOUND`() {
        every { fs.exists(any()) } returns true
        every { fs.exists("/sdcard/WenJuanPro/assets/banner.png") } returns false
        val body =
            """
            # configId: asset-stem
            # title: X
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: img:banner.png|提示
            options: a|b
            correct: 1
            score: 0|0
            """.trimIndent()
        val r = parse(body, "asset-stem.txt")
        assertTrue(r is ParseResult.Failure)
        val err = (r as ParseResult.Failure).errors.first { it.code == ParseErrorCode.ASSET_NOT_FOUND }
        assertEquals("stem", err.field)
    }

    @Test
    fun `1_3-BLIND-ERROR-003 GBK bytes produces ENCODING_INVALID with line 0 and null field`() {
        val gbkBytes =
            "# configId: ok\n# title: 你好\n".toByteArray(Charset.forName("GBK")) +
                "[Q1]\ntype: single\nmode: all_in_one\ndurationMs: 30000\n".toByteArray(Charsets.UTF_8)
        val r = parser.parse("gbk.txt", gbkBytes)
        assertTrue(r is ParseResult.Failure)
        val errors = (r as ParseResult.Failure).errors
        assertEquals(1, errors.size)
        val err = errors[0]
        assertEquals(ParseErrorCode.ENCODING_INVALID, err.code)
        assertEquals(0, err.line)
        assertEquals(null, err.field)
        // sanity
        assertNotNull(err.message)
        assertFalse(err.message.isEmpty())
    }

    // ---------- Mixed Option Content (text + image within single option) ----------

    @Test
    fun `mixed option with text and image via plus delimiter`() {
        val txt = """
            # configId: test
            # title: Test
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: 请选择正确答案
            options: A. +img:opt_a.png|B. +img:opt_b.png|C. 纯文字|img:opt_d.png
            correct: 1
            score: 10|0|0|0
        """.trimIndent()
        val result = parser.parse("test.txt", txt.toByteArray())
        assertTrue("expected valid, errors=${result.errors}", result.errors.isEmpty())
        val q = result.config!!.questions[0] as Question.SingleChoice
        // Option 1: Mixed(Text("A. "), Image("opt_a.png"))
        val opt1 = q.options[0]
        assertTrue("expected Mixed, got $opt1", opt1 is OptionContent.Mixed)
        val parts1 = (opt1 as OptionContent.Mixed).parts
        assertEquals(2, parts1.size)
        assertTrue(parts1[0] is OptionContent.Text)
        assertEquals("A.", (parts1[0] as OptionContent.Text).text.trim())
        assertTrue(parts1[1] is OptionContent.Image)
        assertEquals("opt_a.png", (parts1[1] as OptionContent.Image).fileName)
        // Option 3: pure text (no + delimiter)
        assertTrue(q.options[2] is OptionContent.Text)
        // Option 4: pure image (no + delimiter)
        assertTrue(q.options[3] is OptionContent.Image)
    }

    @Test
    fun `mixed option with text then image then text`() {
        val txt = """
            # configId: test
            # title: Test
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: 题干
            options: 选项A +img:icon_a.png+ 描述A|选项B +img:icon_b.png+ 描述B|C|D
            correct: 1
            score: 10|0|0|0
        """.trimIndent()
        val result = parser.parse("test.txt", txt.toByteArray())
        assertTrue(result.errors.isEmpty())
        val q = result.config!!.questions[0] as Question.SingleChoice
        val opt1 = q.options[0] as OptionContent.Mixed
        assertEquals(3, opt1.parts.size)
        assertTrue(opt1.parts[0] is OptionContent.Text)
        assertTrue(opt1.parts[1] is OptionContent.Image)
        assertTrue(opt1.parts[2] is OptionContent.Text)
    }

    // ---------- Image Size Syntax ----------

    @Test
    fun `image with width and height in stem`() {
        val txt = """
            # configId: test
            # title: Test
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: img:chart.png:400x300
            options: A|B|C|D
            correct: 1
            score: 10|0|0|0
        """.trimIndent()
        val result = parser.parse("test.txt", txt.toByteArray())
        assertTrue(result.errors.isEmpty())
        val q = result.config!!.questions[0] as Question.SingleChoice
        val stem = q.stem as StemContent.Image
        assertEquals("chart.png", stem.fileName)
        assertEquals(400, stem.widthDp)
        assertEquals(300, stem.heightDp)
    }

    @Test
    fun `image with width only in stem`() {
        val txt = """
            # configId: test
            # title: Test
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: img:photo.png:600
            options: A|B|C|D
            correct: 1
            score: 10|0|0|0
        """.trimIndent()
        val result = parser.parse("test.txt", txt.toByteArray())
        assertTrue(result.errors.isEmpty())
        val stem = (result.config!!.questions[0] as Question.SingleChoice).stem as StemContent.Image
        assertEquals("photo.png", stem.fileName)
        assertEquals(600, stem.widthDp)
        assertNull(stem.heightDp)
    }

    @Test
    fun `image with size in option`() {
        val txt = """
            # configId: test
            # title: Test
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: 题干
            options: img:a.png:120x120|img:b.png:120x120|C|D
            correct: 1
            score: 10|0|0|0
        """.trimIndent()
        val result = parser.parse("test.txt", txt.toByteArray())
        assertTrue(result.errors.isEmpty())
        val q = result.config!!.questions[0] as Question.SingleChoice
        val opt1 = q.options[0] as OptionContent.Image
        assertEquals("a.png", opt1.fileName)
        assertEquals(120, opt1.widthDp)
        assertEquals(120, opt1.heightDp)
    }

    @Test
    fun `image with size in mixed option`() {
        val txt = """
            # configId: test
            # title: Test
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: 题干
            options: A. +img:opt_a.png:80x80|B. +img:opt_b.png:80|C|D
            correct: 1
            score: 10|0|0|0
        """.trimIndent()
        val result = parser.parse("test.txt", txt.toByteArray())
        assertTrue(result.errors.isEmpty())
        val q = result.config!!.questions[0] as Question.SingleChoice
        val opt1 = q.options[0] as OptionContent.Mixed
        val img1 = opt1.parts[1] as OptionContent.Image
        assertEquals("opt_a.png", img1.fileName)
        assertEquals(80, img1.widthDp)
        assertEquals(80, img1.heightDp)
        // opt B: width only
        val opt2 = q.options[1] as OptionContent.Mixed
        val img2 = opt2.parts[1] as OptionContent.Image
        assertEquals(80, img2.widthDp)
        assertNull(img2.heightDp)
    }

    @Test
    fun `image without size uses defaults`() {
        val txt = """
            # configId: test
            # title: Test
            [Q1]
            type: single
            mode: all_in_one
            durationMs: 30000
            stem: img:photo.png
            options: img:a.png|B|C|D
            correct: 1
            score: 10|0|0|0
        """.trimIndent()
        val result = parser.parse("test.txt", txt.toByteArray())
        assertTrue(result.errors.isEmpty())
        val stem = (result.config!!.questions[0] as Question.SingleChoice).stem as StemContent.Image
        assertNull(stem.widthDp)
        assertNull(stem.heightDp)
        val opt = (result.config!!.questions[0] as Question.SingleChoice).options[0] as OptionContent.Image
        assertNull(opt.widthDp)
        assertNull(opt.heightDp)
    }
}
