package ai.wenjuanpro.app.ui.components

import ai.wenjuanpro.app.data.parser.ParseError
import ai.wenjuanpro.app.data.parser.ParseErrorCode
import ai.wenjuanpro.app.feature.configlist.ConfigCardUiModel
import ai.wenjuanpro.app.ui.theme.WenJuanProTheme
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performClick
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test

/**
 * Compose UI test skeleton for Story 1.4 — AssessmentCard component.
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 *
 * Run via `./gradlew connectedDebugAndroidTest`.
 */
class AssessmentCardTest {
    @get:Rule
    val composeRule = createComposeRule()

    private fun validModel(): ConfigCardUiModel =
        ConfigCardUiModel(
            configId = "cog-mem",
            title = "认知记忆测评",
            questionCount = 5,
            isValid = true,
            errors = emptyList(),
            sourceFileName = "cog-mem.txt",
        )

    private fun invalidModel(): ConfigCardUiModel =
        ConfigCardUiModel(
            configId = "broken",
            title = "broken.txt",
            questionCount = null,
            isValid = false,
            errors =
                listOf(
                    ParseError(
                        line = 2,
                        field = "title",
                        code = ParseErrorCode.CONFIG_FIELD_INVALID,
                        message = "broken.txt: 第 2 行缺少必填字段 title",
                    ),
                ),
            sourceFileName = "broken.txt",
        )

    @Test
    fun `1_4-E2E-001 Valid card click invokes onClick`() {
        var clicks = 0
        val model = validModel()
        composeRule.setContent {
            WenJuanProTheme {
                AssessmentCard(
                    model = model,
                    onClick = { clicks++ },
                    onViewErrors = {},
                )
            }
        }
        composeRule
            .onNodeWithTag(AssessmentCardTags.VALID_CARD_PREFIX + model.sourceFileName)
            .performClick()
        assertEquals(1, clicks)
    }

    @Test
    fun `1_4-E2E-002 Invalid card entire body does NOT invoke onClick`() {
        var clicks = 0
        val model = invalidModel()
        composeRule.setContent {
            WenJuanProTheme {
                AssessmentCard(
                    model = model,
                    onClick = { clicks++ },
                    onViewErrors = {},
                )
            }
        }
        composeRule
            .onNodeWithTag(AssessmentCardTags.INVALID_CARD_PREFIX + model.sourceFileName)
            .performClick()
        assertEquals(0, clicks)
    }

    @Test
    fun `1_4-E2E-003 Invalid card '查看错误详情' TextButton invokes onViewErrors`() {
        var viewErrors = 0
        val model = invalidModel()
        composeRule.setContent {
            WenJuanProTheme {
                AssessmentCard(
                    model = model,
                    onClick = {},
                    onViewErrors = { viewErrors++ },
                )
            }
        }
        composeRule
            .onNodeWithTag(AssessmentCardTags.VIEW_ERRORS_BUTTON_PREFIX + model.sourceFileName)
            .performClick()
        assertEquals(1, viewErrors)
    }

    @Test
    fun `1_4-BLIND-BOUNDARY-005 Very long title (80 chars) truncates with maxLines=1 ellipsis`() {
        val longTitle = "a".repeat(80)
        val model = validModel().copy(title = longTitle)
        composeRule.setContent {
            WenJuanProTheme {
                AssessmentCard(
                    model = model,
                    onClick = {},
                    onViewErrors = {},
                )
            }
        }
        // The card must exist and remain clickable; title truncation is enforced by maxLines=1 in component.
        composeRule
            .onNodeWithTag(AssessmentCardTags.VALID_CARD_PREFIX + model.sourceFileName)
            .assertIsDisplayed()
        // Verify card height does not blow up past a single-row ceiling.
        val bounds =
            composeRule
                .onNodeWithTag(AssessmentCardTags.VALID_CARD_PREFIX + model.sourceFileName)
                .fetchSemanticsNode()
                .boundsInRoot
        assertTrue("card height should stay below 2× baseline 96dp", bounds.height < 400f)
    }
}
