package ai.wenjuanpro.app.ui.components

import ai.wenjuanpro.app.data.parser.ParseError
import ai.wenjuanpro.app.data.parser.ParseErrorCode
import ai.wenjuanpro.app.ui.theme.WenJuanProTheme
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.hasText
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onAllNodes
import androidx.compose.ui.test.onFirst
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performClick
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test

/**
 * Compose UI test skeleton for Story 1.4 — ErrorSheet (ModalBottomSheet).
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 */
class ErrorSheetTest {
    @get:Rule
    val composeRule = createComposeRule()

    private fun errors(): List<ParseError> =
        listOf(
            ParseError(
                line = 2,
                field = "title",
                code = ParseErrorCode.CONFIG_FIELD_INVALID,
                message = "缺少必填字段 title",
            ),
            ParseError(
                line = 5,
                field = null,
                code = ParseErrorCode.CONFIG_FIELD_INVALID,
                message = "未识别的行",
            ),
            ParseError(
                line = 7,
                field = "durationMs",
                code = ParseErrorCode.CONFIG_FIELD_INVALID,
                message = "不合法的数值",
            ),
        )

    @Test
    fun `1_4-E2E-004 Three ParseErrors render as three formatted rows with monospace font`() {
        composeRule.setContent {
            WenJuanProTheme {
                ErrorSheet(errors = errors(), onDismiss = {})
            }
        }
        composeRule.onAllNodes(hasText("第 2 行", substring = true)).onFirst().assertIsDisplayed()
        composeRule.onAllNodes(hasText("第 5 行", substring = true)).onFirst().assertIsDisplayed()
        composeRule.onAllNodes(hasText("第 7 行", substring = true)).onFirst().assertIsDisplayed()
    }

    @Test
    fun `1_4-E2E-005 Close IconButton invokes onDismiss`() {
        var dismissed = 0
        composeRule.setContent {
            WenJuanProTheme {
                ErrorSheet(errors = errors(), onDismiss = { dismissed++ })
            }
        }
        composeRule.onNodeWithTag(ErrorSheetTags.CLOSE_BUTTON).performClick()
        assertEquals(1, dismissed)
    }

    @Test
    fun `1_4-BLIND-ERROR-003 ParseError with field=null renders '—' placeholder (not 'null')`() {
        composeRule.setContent {
            WenJuanProTheme {
                ErrorSheet(
                    errors =
                        listOf(
                            ParseError(
                                line = 2,
                                field = null,
                                code = ParseErrorCode.CONFIG_FIELD_INVALID,
                                message = "unknown",
                            ),
                        ),
                    onDismiss = {},
                )
            }
        }
        composeRule.onAllNodes(hasText("第 2 行 · — · unknown", substring = false)).onFirst().assertIsDisplayed()
    }
}
