package ai.wenjuanpro.app.ui.components

import androidx.compose.foundation.layout.size
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.test.ExperimentalTestApi
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performTouchInput
import androidx.compose.ui.unit.dp
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test

/**
 * Compose UI test skeleton for Story 1.4 — HiddenLongPressArea (5s threshold, zero visual feedback).
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 *
 * Uses a test-short threshold (200ms) to keep the instrumented run fast while still validating
 * the >= boundary semantics. The 5000ms production default is validated on-device (see Dev Log).
 */
@OptIn(ExperimentalTestApi::class)
class HiddenLongPressAreaTest {
    @get:Rule
    val composeRule = createComposeRule()

    private val testThresholdMs = 200L

    @Test
    fun `1_4-E2E-006 Press-and-hold 5_100 ms triggers onTriggered`() {
        var triggered = 0
        composeRule.setContent {
            HiddenLongPressArea(
                onTriggered = { triggered++ },
                modifier = Modifier.size(64.dp),
                thresholdMs = testThresholdMs,
            )
        }
        composeRule.onNodeWithTag(HiddenLongPressAreaTags.ROOT).performTouchInput {
            down(center)
        }
        Thread.sleep(testThresholdMs + 100)
        composeRule.onNodeWithTag(HiddenLongPressAreaTags.ROOT).performTouchInput { up() }
        composeRule.waitForIdle()
        assertEquals(1, triggered)
    }

    @Test
    fun `1_4-E2E-007 Press-and-hold 4_900 ms does NOT trigger onTriggered`() {
        var triggered = 0
        composeRule.setContent {
            HiddenLongPressArea(
                onTriggered = { triggered++ },
                modifier = Modifier.size(64.dp),
                thresholdMs = testThresholdMs,
            )
        }
        composeRule.onNodeWithTag(HiddenLongPressAreaTags.ROOT).performTouchInput {
            down(center)
        }
        Thread.sleep(testThresholdMs - 100)
        composeRule.onNodeWithTag(HiddenLongPressAreaTags.ROOT).performTouchInput { up() }
        composeRule.waitForIdle()
        assertEquals(0, triggered)
    }

    @Test
    fun `1_4-BLIND-BOUNDARY-006 Press-and-hold exactly 5_000 ms triggers onTriggered (>= boundary)`() {
        var triggered = 0
        composeRule.setContent {
            HiddenLongPressArea(
                onTriggered = { triggered++ },
                modifier = Modifier.size(64.dp),
                thresholdMs = testThresholdMs,
            )
        }
        composeRule.onNodeWithTag(HiddenLongPressAreaTags.ROOT).performTouchInput {
            down(center)
        }
        Thread.sleep(testThresholdMs)
        composeRule.onNodeWithTag(HiddenLongPressAreaTags.ROOT).performTouchInput { up() }
        composeRule.waitForIdle()
        assertEquals(1, triggered)
    }

    @Test
    fun `1_4-BLIND-FLOW-004 Finger sliding off area before 5s does not trigger`() {
        var triggered = 0
        composeRule.setContent {
            HiddenLongPressArea(
                onTriggered = { triggered++ },
                modifier = Modifier.size(64.dp),
                thresholdMs = testThresholdMs,
            )
        }
        composeRule.onNodeWithTag(HiddenLongPressAreaTags.ROOT).performTouchInput {
            down(center)
            moveBy(Offset(x = 1_000f, y = 1_000f))
        }
        Thread.sleep(50)
        composeRule.onNodeWithTag(HiddenLongPressAreaTags.ROOT).performTouchInput { up() }
        composeRule.waitForIdle()
        assertEquals(0, triggered)
    }
}
