package ai.wenjuanpro.app.domain.usecase

import ai.wenjuanpro.app.data.config.ConfigLoadResult
import ai.wenjuanpro.app.data.config.ConfigRepository
import ai.wenjuanpro.app.data.parser.ParseError
import ai.wenjuanpro.app.data.parser.ParseErrorCode
import ai.wenjuanpro.app.domain.model.Config
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.mockk
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Test skeleton for Story 1.4 — LoadConfigsUseCase (thin wrapper around ConfigRepository.loadAll).
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 */
class LoadConfigsUseCaseTest {
    private fun invalid(fileName: String = "broken.txt"): ConfigLoadResult.Invalid =
        ConfigLoadResult.Invalid(
            fileName = fileName,
            errors =
                listOf(
                    ParseError(
                        line = 2,
                        field = null,
                        code = ParseErrorCode.CONFIG_FIELD_INVALID,
                        message = "m",
                    ),
                ),
        )

    private fun valid(configId: String = "a-cfg"): ConfigLoadResult.Valid =
        ConfigLoadResult.Valid(
            Config(configId = configId, title = "T", sourceFileName = "$configId.txt", questions = emptyList()),
        )

    @Test
    fun `1_4-UNIT-019 invoke delegates to repository loadAll and returns the same list`() =
        runTest {
            val repo = mockk<ConfigRepository>()
            val preset = listOf(valid("a-cfg"), invalid("broken.txt"), valid("b-cfg"))
            coEvery { repo.loadAll() } returns preset

            val useCase = LoadConfigsUseCase(repo)
            val actual = useCase()

            assertEquals(preset, actual)
            coVerify(exactly = 1) { repo.loadAll() }
        }

    @Test
    fun `1_4-UNIT-020 invoke returns empty list when repository returns empty`() =
        runTest {
            val repo = mockk<ConfigRepository>()
            coEvery { repo.loadAll() } returns emptyList()

            val useCase = LoadConfigsUseCase(repo)
            val actual = useCase()

            assertTrue(actual.isEmpty())
        }
}
