package ai.wenjuanpro.app.data.config

import ai.wenjuanpro.app.core.io.FileSystem
import ai.wenjuanpro.app.data.parser.ConfigParser
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.Runnable
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.IOException
import kotlin.coroutines.CoroutineContext

/**
 * Test Skeleton for Story 1.3 — ConfigRepositoryImpl.
 *
 * AUTO-GENERATED by QA Test Design (Turing, 2026-04-17). Dev MUST implement every test block.
 * Scenarios map to docs/qa/assessments/1.3-test-design-20260417.md.
 */
@OptIn(ExperimentalCoroutinesApi::class)
class ConfigRepositoryImplTest {
    private val configDir = "/sdcard/WenJuanPro/config/"

    private fun validBody(configId: String): ByteArray =
        """
        # configId: $configId
        # title: T
        [Q1]
        type: single
        mode: all_in_one
        durationMs: 30000
        stem: A
        options: a|b
        correct: 1
        score: 0|0
        """.trimIndent().toByteArray(Charsets.UTF_8)

    private fun badBody(): ByteArray =
        """
        # configId: bad
        [Q1]
        type: single
        mode: all_in_one
        durationMs: 30000
        stem: A
        options: a|b
        correct: 1
        score: 0|0
        """.trimIndent().toByteArray(Charsets.UTF_8)

    private fun fileSystem(
        files: List<String>,
        contents: Map<String, ByteArray> = emptyMap(),
        throwers: Set<String> = emptySet(),
    ): FileSystem {
        val fs = mockk<FileSystem>()
        every { fs.exists(any()) } returns true
        every { fs.listFiles(configDir, ".txt") } returns files
        for (path in files) {
            if (path in throwers) {
                every { fs.readBytes(path) } throws IOException("boom")
            } else {
                every { fs.readBytes(path) } returns (contents[path] ?: validBody("default"))
            }
        }
        return fs
    }

    private fun repo(fs: FileSystem, dispatcher: CoroutineDispatcher): ConfigRepositoryImpl =
        ConfigRepositoryImpl(fs, ConfigParser(fs), dispatcher)

    // ============================================================
    // AC1 — Core Integration
    // ============================================================

    @Test
    fun `1_3-INT-001 loadAll returns Valid and Invalid when two files one legal one corrupt`() =
        runTest {
            val okPath = configDir + "ok.txt"
            val badPath = configDir + "bad.txt"
            val fs =
                fileSystem(
                    files = listOf(okPath, badPath),
                    contents =
                        mapOf(
                            okPath to validBody("ok-cfg"),
                            badPath to badBody(),
                        ),
                )
            val results = repo(fs, StandardTestDispatcher(testScheduler)).loadAll()
            assertEquals(2, results.size)
            assertEquals(1, results.filterIsInstance<ConfigLoadResult.Valid>().size)
            val invalid = results.filterIsInstance<ConfigLoadResult.Invalid>().first()
            assertEquals("bad.txt", invalid.fileName)
            assertTrue(invalid.errors.isNotEmpty())
        }

    @Test
    fun `1_3-INT-002 empty directory returns empty list`() =
        runTest {
            val fs = fileSystem(files = emptyList())
            val results = repo(fs, StandardTestDispatcher(testScheduler)).loadAll()
            assertTrue(results.isEmpty())
        }

    @Test
    fun `1_3-INT-003 nonexistent directory returns empty list without throwing`() =
        runTest {
            val fs = mockk<FileSystem>()
            every { fs.exists(any()) } returns false
            every { fs.listFiles(configDir, ".txt") } returns emptyList()
            val results = repo(fs, StandardTestDispatcher(testScheduler)).loadAll()
            assertTrue(results.isEmpty())
        }

    @Test
    fun `1_3-INT-004 three valid files all map to Valid`() =
        runTest {
            val paths =
                listOf("a-cfg.txt", "b-cfg.txt", "c-cfg.txt").map { configDir + it }
            val fs =
                fileSystem(
                    files = paths,
                    contents =
                        mapOf(
                            paths[0] to validBody("a-cfg"),
                            paths[1] to validBody("b-cfg"),
                            paths[2] to validBody("c-cfg"),
                        ),
                )
            val results = repo(fs, StandardTestDispatcher(testScheduler)).loadAll()
            assertEquals(3, results.size)
            assertTrue(results.all { it is ConfigLoadResult.Valid })
        }

    @Test
    fun `1_3-INT-005 loadAll executes on injected IoDispatcher`() =
        runTest {
            val recorder = RecordingDispatcher(StandardTestDispatcher(testScheduler))
            val okPath = configDir + "ok.txt"
            val fs =
                fileSystem(
                    files = listOf(okPath),
                    contents = mapOf(okPath to validBody("ok-cfg")),
                )
            repo(fs, recorder).loadAll()
            assertTrue(
                "withContext should dispatch through injected IoDispatcher",
                recorder.dispatchCount > 0,
            )
        }

    @Test
    fun `1_3-INT-006 results sorted by configId ascending stable`() =
        runTest {
            val paths =
                listOf("z.txt", "a.txt", "m.txt").map { configDir + it }
            val fs =
                fileSystem(
                    files = paths,
                    contents =
                        mapOf(
                            paths[0] to validBody("z-cfg"),
                            paths[1] to validBody("a-cfg"),
                            paths[2] to validBody("m-cfg"),
                        ),
                )
            val results = repo(fs, StandardTestDispatcher(testScheduler)).loadAll()
            val ids =
                results.map {
                    when (it) {
                        is ConfigLoadResult.Valid -> it.config.configId
                        is ConfigLoadResult.Invalid -> it.fileName
                    }
                }
            assertEquals(listOf("a-cfg", "m-cfg", "z-cfg"), ids)
        }

    // ============================================================
    // AC1 — [BLIND-SPOT] ERROR
    // ============================================================

    @Test
    fun `1_3-BLIND-ERROR-004 readBytes IOException handled gracefully without crashing loadAll`() =
        runTest {
            val okPath = configDir + "ok.txt"
            val badPath = configDir + "boom.txt"
            val fs =
                fileSystem(
                    files = listOf(okPath, badPath),
                    contents = mapOf(okPath to validBody("ok-cfg")),
                    throwers = setOf(badPath),
                )
            val results = repo(fs, StandardTestDispatcher(testScheduler)).loadAll()
            assertEquals(2, results.size)
            val invalid = results.filterIsInstance<ConfigLoadResult.Invalid>().first()
            assertEquals("boom.txt", invalid.fileName)
            assertTrue(invalid.errors.isNotEmpty())
        }

    // ============================================================
    // AC1 — [BLIND-SPOT] CONCURRENCY
    // ============================================================

    @Test
    fun `1_3-BLIND-CONCURRENCY-001 concurrent loadAll calls return consistent results`() =
        runTest {
            val paths =
                listOf("a.txt", "b.txt", "c.txt").map { configDir + it }
            val fs =
                fileSystem(
                    files = paths,
                    contents =
                        mapOf(
                            paths[0] to validBody("a-cfg"),
                            paths[1] to validBody("b-cfg"),
                            paths[2] to validBody("c-cfg"),
                        ),
                )
            val r = repo(fs, StandardTestDispatcher(testScheduler))
            val results = listOf(async { r.loadAll() }, async { r.loadAll() }, async { r.loadAll() }).awaitAll()
            assertEquals(results[0], results[1])
            assertEquals(results[1], results[2])
        }

    // ---- Helpers ----

    private class RecordingDispatcher(private val delegate: CoroutineDispatcher) : CoroutineDispatcher() {
        var dispatchCount = 0
            private set

        override fun dispatch(context: CoroutineContext, block: Runnable) {
            dispatchCount++
            delegate.dispatch(context, block)
        }

        override fun isDispatchNeeded(context: CoroutineContext): Boolean = true
    }
}
