package ai.wenjuanpro.app.data.config

import ai.wenjuanpro.app.core.io.FileSystem
import ai.wenjuanpro.app.data.parser.ConfigParser
import io.mockk.every
import io.mockk.mockk
import io.mockk.verify
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.Runnable
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.coroutines.CoroutineContext
import kotlinx.coroutines.CoroutineDispatcher

/**
 * Test skeleton for Story 1.4 — ConfigRepositoryImpl.ensureConfigDir() extension.
 *
 * AUTO-GENERATED by QA Test Design 2026-04-17.
 * Source: docs/qa/assessments/1.4-test-design-20260417.md
 */
@OptIn(ExperimentalCoroutinesApi::class)
class ConfigRepositoryImplEnsureConfigDirTest {
    private val configDir = "/sdcard/WenJuanPro/config/"

    private fun repo(
        fs: FileSystem,
        dispatcher: CoroutineDispatcher,
    ): ConfigRepositoryImpl = ConfigRepositoryImpl(fs, ConfigParser(fs), dispatcher)

    @Test
    fun `1_4-INT-004 ensureConfigDir creates directory when exists=false and runs on ioDispatcher`() =
        runTest {
            val fs = mockk<FileSystem>()
            every { fs.exists(configDir) } returns false
            every { fs.mkdirs(configDir) } returns true

            val recorder = RecordingDispatcher(StandardTestDispatcher(testScheduler))
            val result = repo(fs, recorder).ensureConfigDir()

            assertTrue(result)
            verify(exactly = 1) { fs.mkdirs(configDir) }
            assertTrue(
                "ensureConfigDir must dispatch through injected IoDispatcher",
                recorder.dispatchCount > 0,
            )
        }

    @Test
    fun `1_4-INT-005 ensureConfigDir is a no-op when directory already exists`() =
        runTest {
            val fs = mockk<FileSystem>()
            every { fs.exists(configDir) } returns true

            val result = repo(fs, StandardTestDispatcher(testScheduler)).ensureConfigDir()

            assertTrue(result)
            verify(exactly = 0) { fs.mkdirs(any()) }
        }

    @Test
    fun `1_4-BLIND-ERROR-002 mkdirs failure returns false and subsequent loadAll yields Empty (not Error)`() =
        runTest {
            val fs = mockk<FileSystem>()
            every { fs.exists(configDir) } returns false
            every { fs.mkdirs(configDir) } returns false
            every { fs.listFiles(configDir, ".txt") } returns emptyList()

            val r = repo(fs, StandardTestDispatcher(testScheduler))
            val ensured = r.ensureConfigDir()
            assertFalse(ensured)

            val loaded = r.loadAll()
            assertEquals(emptyList<ConfigLoadResult>(), loaded)
        }

    private class RecordingDispatcher(private val delegate: CoroutineDispatcher) : CoroutineDispatcher() {
        var dispatchCount = 0
            private set

        override fun dispatch(
            context: CoroutineContext,
            block: Runnable,
        ) {
            dispatchCount++
            delegate.dispatch(context, block)
        }

        override fun isDispatchNeeded(context: CoroutineContext): Boolean = true
    }
}
